import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import '../theme/app_colors.dart';
import '../widgets/custom_button.dart';

class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key});

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {
  final PageController _pageController = PageController();
  int _currentIndex = 0;

  final List<OnboardingData> _pages = [
    OnboardingData(
      title: 'Track Every Step',
      description: 'Automatically count steps, monitor active duration, and calculate calorie shredding with crystal-clear daily metrics.',
      icon: Icons.directions_walk_rounded,
      glowColor: AppColors.primary,
    ),
    OnboardingData(
      title: 'AI Walking Coach',
      description: 'Receive custom health plans and daily motivational feedback generated by our intelligent coach, tailored to your routine.',
      icon: Icons.chat_bubble_rounded,
      glowColor: AppColors.accent,
    ),
    OnboardingData(
      title: 'GPS Route Tracking',
      description: 'Draw your outdoor workout maps accurately with speed indicators, altitude gain trackers, and average paces.',
      icon: Icons.map_rounded,
      glowColor: AppColors.secondary,
    ),
    OnboardingData(
      title: 'Rewards & Challenges',
      description: 'Join daily activities to earn Stride Coins, complete unlock milestones, and cash out premium merchandise or gift card rewards.',
      icon: Icons.emoji_events_rounded,
      glowColor: AppColors.primary,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: isDark ? AppColors.darkBgGradient : const LinearGradient(
            colors: [Color(0xFFF1F5F9), Color(0xFFF8FAFC)],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              // Skip Button
              Align(
                alignment: Alignment.topRight,
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: TextButton(
                    onPressed: () => Navigator.of(context).pushReplacementNamed('/login'),
                    child: Text(
                      'Skip',
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: AppColors.primary,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),
              ),

              // Page View
              Expanded(
                child: PageView.builder(
                  controller: _pageController,
                  itemCount: _pages.length,
                  onPageChanged: (index) {
                    setState(() {
                      _currentIndex = index;
                    });
                  },
                  itemBuilder: (context, index) {
                    final item = _pages[index];
                    return SingleChildScrollView(
                      padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 16.0),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const SizedBox(height: 20),
                          // Vector Placeholder with breathing glow ring
                          Container(
                            width: 300,
                            height: 220,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(24),
                              color: isDark ? const Color(0xFF161E2E) : Colors.white,
                              border: Border.all(
                                color: item.glowColor.withOpacity(0.2),
                                width: 2,
                              ),
                              boxShadow: [
                                BoxShadow(
                                  color: item.glowColor.withOpacity(0.15),
                                  blurRadius: 32,
                                  offset: const Offset(0, 10),
                                ),
                              ],
                            ),
                            child: index == 0
                                ? ClipRRect(
                                    borderRadius: BorderRadius.circular(22),
                                    child: Image.asset(
                                      'assets/first.gif',
                                      fit: BoxFit.cover,
                                    ),
                                  )
                                : index == 1
                                    ? ClipRRect(
                                        borderRadius: BorderRadius.circular(22),
                                        child: AssetVideoPlayer(
                                          assetPath: 'assets/second.mp4',
                                          isActive: _currentIndex == 1,
                                        ),
                                      )
                                    : index == 2
                                        ? ClipRRect(
                                            borderRadius: BorderRadius.circular(22),
                                            child: AssetVideoPlayer(
                                              assetPath: 'assets/third.mp4',
                                              isActive: _currentIndex == 2,
                                            ),
                                          )
                                        : index == 3
                                            ? ClipRRect(
                                                borderRadius: BorderRadius.circular(22),
                                                child: AssetVideoPlayer(
                                                  assetPath: 'assets/fourth.mp4',
                                                  isActive: _currentIndex == 3,
                                                ),
                                              )
                                            : Icon(
                                                item.icon,
                                                size: 100,
                                                color: item.glowColor,
                                              ),
                          ),
                          const SizedBox(height: 36),
                          Text(
                            item.title,
                            textAlign: TextAlign.center,
                            style: theme.textTheme.displayMedium?.copyWith(
                              fontWeight: FontWeight.bold,
                              fontFamily: 'Outfit',
                            ),
                          ),
                          const SizedBox(height: 16),
                          Text(
                            item.description,
                            textAlign: TextAlign.center,
                            style: theme.textTheme.bodyMedium?.copyWith(
                              fontSize: 15,
                              height: 1.6,
                              color: isDark ? AppColors.textSecondaryDark : AppColors.textSecondaryLight,
                            ),
                          ),
                          const SizedBox(height: 20),
                        ],
                      ),
                    );
                  },
                ),
              ),

              // Bottom Actions Area
              Padding(
                padding: const EdgeInsets.all(32.0),
                child: Column(
                  children: [
                    // Dot Indicator
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: List.generate(_pages.length, (index) {
                        final isActive = index == _currentIndex;
                        return AnimatedContainer(
                          duration: const Duration(milliseconds: 300),
                          margin: const EdgeInsets.symmetric(horizontal: 5),
                          height: 8,
                          width: isActive ? 24 : 8,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(10),
                            color: isActive
                                ? AppColors.primary
                                : (isDark ? const Color(0xFF334155) : const Color(0xFFCBD5E1)),
                          ),
                        );
                      }),
                    ),
                    const SizedBox(height: 32),
                    // Action Buttons
                    if (_currentIndex == _pages.length - 1)
                      CustomButton(
                        text: 'Get Started',
                        onPressed: () => Navigator.of(context).pushReplacementNamed('/login'),
                        type: ButtonType.primary,
                      )
                    else
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          // Previous Button (Hidden on first page)
                          _currentIndex > 0
                              ? IconButton(
                                  onPressed: () {
                                    _pageController.previousPage(
                                      duration: const Duration(milliseconds: 400),
                                      curve: Curves.easeInOut,
                                    );
                                  },
                                  icon: const Icon(Icons.arrow_back_ios_new_rounded),
                                )
                              : const SizedBox(width: 48),
                          // Next Button
                          CustomButton(
                            text: 'Next',
                            onPressed: () {
                              _pageController.nextPage(
                                duration: const Duration(milliseconds: 400),
                                curve: Curves.easeInOut,
                              );
                            },
                            width: 140,
                            height: 52,
                            type: ButtonType.primary,
                          ),
                        ],
                      ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class OnboardingData {
  final String title;
  final String description;
  final IconData icon;
  final Color glowColor;

  OnboardingData({
    required this.title,
    required this.description,
    required this.icon,
    required this.glowColor,
  });
}

class AssetVideoPlayer extends StatefulWidget {
  final String assetPath;
  final bool isActive;
  const AssetVideoPlayer({super.key, required this.assetPath, required this.isActive});

  @override
  State<AssetVideoPlayer> createState() => _AssetVideoPlayerState();
}

class _AssetVideoPlayerState extends State<AssetVideoPlayer> {
  late VideoPlayerController _controller;
  bool _isInitialized = false;
  bool _hasError = false;

  @override
  void initState() {
    super.initState();
    _initPlayer();
  }

  void _initPlayer() {
    _controller = VideoPlayerController.asset(widget.assetPath)
      ..initialize().then((_) {
        if (mounted) {
          setState(() {
            _isInitialized = true;
          });
          _controller.setLooping(true);
          _controller.setVolume(0.0); // Mute onboarding video
          if (widget.isActive) {
            _controller.play();
          }
        }
      }).catchError((error) {
        debugPrint('Error initializing video player: $error');
        if (mounted) {
          setState(() {
            _hasError = true;
          });
        }
      });
  }

  @override
  void didUpdateWidget(covariant AssetVideoPlayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (_isInitialized) {
      if (widget.isActive && !oldWidget.isActive) {
        _controller.play();
      } else if (!widget.isActive && oldWidget.isActive) {
        _controller.pause();
      }
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_hasError) {
      return const Center(
        child: Icon(
          Icons.error_outline_rounded,
          size: 48,
          color: Colors.redAccent,
        ),
      );
    }

    if (!_isInitialized) {
      return Center(
        child: CircularProgressIndicator(
          valueColor: AlwaysStoppedAnimation<Color>(AppColors.accent),
        ),
      );
    }

    return SizedBox.expand(
      child: FittedBox(
        fit: BoxFit.cover,
        child: SizedBox(
          width: _controller.value.size.width,
          height: _controller.value.size.height,
          child: VideoPlayer(_controller),
        ),
      ),
    );
  }
}
